package dev.mariscore.currency;
import dev.mariscore.*;import dev.mariscore.config.Settings;import dev.mariscore.storage.Storage;import net.milkbowl.vault.economy.*;import org.bukkit.OfflinePlayer;import java.math.*;import java.util.*;
public final class MarisEconomy implements Economy{private final MarisCorePlugin p;private final Storage s;private final Settings cfg; public MarisEconomy(MarisCorePlugin p,Storage s,Settings cfg){this.p=p;this.s=s;this.cfg=cfg;}
 public boolean isEnabled(){return p.isEnabled()&&!s.isClosed();} public String getName(){return "MarisCore";} public boolean hasBankSupport(){return false;} public int fractionalDigits(){return 2;} public String format(double a){return "$"+dev.mariscore.util.Money.fmt(BigDecimal.valueOf(a));} public String currencyNamePlural(){return "money";} public String currencyNameSingular(){return "money";}
 public boolean hasAccount(String n){return !s.isClosed()&&s.byName(n).join().isPresent();} public boolean hasAccount(OfflinePlayer p){return s.cached(p.getUniqueId()).isPresent();} public boolean hasAccount(String n,String w){return hasAccount(n);} public boolean hasAccount(OfflinePlayer p,String w){return hasAccount(p);} public boolean createPlayerAccount(String n){return true;} public boolean createPlayerAccount(OfflinePlayer op){if(s.isClosed())return false;s.ensure(op.getUniqueId(),op.getName()==null?op.getUniqueId().toString():op.getName(),cfg.startingMoney,cfg.startingShards).join();return true;} public boolean createPlayerAccount(String n,String w){return createPlayerAccount(n);} public boolean createPlayerAccount(OfflinePlayer p,String w){return createPlayerAccount(p);}
 public double getBalance(String n){return s.byName(n).join().map(Storage.Account::money).orElse(BigDecimal.ZERO).doubleValue();} public double getBalance(OfflinePlayer p){return s.balanceCached(p.getUniqueId(),"money").doubleValue();} public double getBalance(String n,String w){return getBalance(n);} public double getBalance(OfflinePlayer p,String w){return getBalance(p);} public boolean has(String n,double a){return getBalance(n)>=a;} public boolean has(OfflinePlayer p,double a){return getBalance(p)>=a;} public boolean has(String n,String w,double a){return has(n,a);} public boolean has(OfflinePlayer p,String w,double a){return has(p,a);} 
 public EconomyResponse withdrawPlayer(String n,double a){return s.byName(n).join().map(ac->withdraw(ac.uuid(),a)).orElse(new EconomyResponse(0,0,EconomyResponse.ResponseType.FAILURE,"Account not found"));} public EconomyResponse withdrawPlayer(OfflinePlayer p,double a){return withdraw(p.getUniqueId(),a);} public EconomyResponse withdrawPlayer(String n,String w,double a){return withdrawPlayer(n,a);} public EconomyResponse withdrawPlayer(OfflinePlayer p,String w,double a){return withdrawPlayer(p,a);} private EconomyResponse withdraw(UUID id,double a){if(a<0)return new EconomyResponse(0,0,EconomyResponse.ResponseType.FAILURE,"Negative amount"); BigDecimal bal=s.balanceCached(id,"money"), amt=BigDecimal.valueOf(a); if(bal.compareTo(amt)<0)return new EconomyResponse(0,bal.doubleValue(),EconomyResponse.ResponseType.FAILURE,"Insufficient funds"); s.add(id,"money",amt.negate()).join(); return new EconomyResponse(a,bal.subtract(amt).doubleValue(),EconomyResponse.ResponseType.SUCCESS,null);} 
 public EconomyResponse depositPlayer(String n,double a){return s.byName(n).join().map(ac->deposit(ac.uuid(),a)).orElse(new EconomyResponse(0,0,EconomyResponse.ResponseType.FAILURE,"Account not found"));} public EconomyResponse depositPlayer(OfflinePlayer p,double a){return deposit(p.getUniqueId(),a);} public EconomyResponse depositPlayer(String n,String w,double a){return depositPlayer(n,a);} public EconomyResponse depositPlayer(OfflinePlayer p,String w,double a){return depositPlayer(p,a);} private EconomyResponse deposit(UUID id,double a){if(a<0)return new EconomyResponse(0,0,EconomyResponse.ResponseType.FAILURE,"Negative amount"); BigDecimal amt=BigDecimal.valueOf(a); BigDecimal bal=s.balanceCached(id,"money").add(amt); s.add(id,"money",amt).join(); return new EconomyResponse(a,bal.doubleValue(),EconomyResponse.ResponseType.SUCCESS,null);} 
 public EconomyResponse createBank(String n,String p){return bankFail();} public EconomyResponse createBank(String n,OfflinePlayer p){return bankFail();} public EconomyResponse deleteBank(String n){return bankFail();} public EconomyResponse bankBalance(String n){return bankFail();} public EconomyResponse bankHas(String n,double a){return bankFail();} public EconomyResponse bankWithdraw(String n,double a){return bankFail();} public EconomyResponse bankDeposit(String n,double a){return bankFail();} public EconomyResponse isBankOwner(String n,String p){return bankFail();} public EconomyResponse isBankOwner(String n,OfflinePlayer p){return bankFail();} public EconomyResponse isBankMember(String n,String p){return bankFail();} public EconomyResponse isBankMember(String n,OfflinePlayer p){return bankFail();} public List<String> getBanks(){return List.of();} private EconomyResponse bankFail(){return new EconomyResponse(0,0,EconomyResponse.ResponseType.NOT_IMPLEMENTED,"Banks are not supported");}
}
